name: update-friends-posts

on: 
  push:
    branches: 
     - master
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      working-directory: ./hexo_circle_of_friends
      run: |
        pip install -r requirements.txt
    
    - name: websave spider
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -u ./hexo_circle_of_friends/websave_spider.py $github-token

    - name: sqlite Update posts # sqlite
      env:
        SQLITE_DB: ${{ secrets.SQLITE_DB }}
      run: |
        python -u ./hexo_circle_of_friends/run.py

    - name: Push sqlite data # sqlite push
      uses: swinton/commit@v2.x
      env:
        GH_NAME: noionion
        GH_EMAIL: noionion@outlook.com
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          data.db
        commit-message: Committing ./myfile
        ref: refs/heads/my-branch