name: update-friends-posts

on: 
  push:
    branches: 
     - master
  schedule:
    - cron: "0 0,8,16,24 * * *"
  watch:
    types: [started]

env:
  # sqlite配置，用于将db文件上传到github仓库
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      working-directory: ./hexo_circle_of_friends
      run: |
        pip install -r requirements.txt
    
    - name: sqlite Update posts # sqlite
      env:
        SQLITE_DB: ${{ secrets.SQLITE_DB }}
      run: |
        python ./hexo_circle_of_friends/run.py

    - name: Push sqlite data # sqlite push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update data.db"
        files: data.db
        rebase: 'true'
        name: ${{ env.GITHUB_NAME }}
        email: ${{ env.GITHUB_EMAIL }}